{% set name = "libwgrib2" %}
# {% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set version = "v3.0.0" %}
# {% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}
{% set build_number = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  skip: true    # [win]
  number: {{ build_number }}
  # string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}

  # If the installation is complex, or different between Unix and Windows,
  # use separate bld.bat and build.sh files instead of this key. By default,
  # the package will be built for the Python versions supported by conda-forge
  # and for all major OSs. Add the line "skip: True  # [py<35]" (for example)
  # to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit
  # to Windows.
  # script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required
    # compilers as separate entries here. Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
  host:
    - libnetcdf * nompi_*
    - libaec
    - libpng
    - jasper
    - _openmp_mutex # [linux]
    - llvm-openmp   # [osx]
  run:
    - libnetcdf * nompi_*
    - libaec
    - libpng
    - jasper

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  # imports:
  # Run your test commands here
  commands:
    - pytest
  # declare any test-only requirements here
  requires:
    - pytest
  # copy over any needed test files here
  source_files:
    - tests/

# Uncomment and fill in libwgrib2 metadata
about:
  home: https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2
  license: PUBLIC-DOMAIN
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: Shared library to manipulate GRIB2 files

# Uncomment the following if this will be on a forge
# Remove these lines if this is only be used for CI
extra:
  recipe-maintainers:
    - yt87
